# Site settings
name: GoDaddy Open Source Center
email: opensource@godaddy.com
description: > # this means to ignore newlines until the next key
  Official GoDaddy open source engineering page, showcasing
  open source libraries and projects created by GoDaddy 
  engineering teams. 
url: "https://godaddy.github.io"

twitter_username: GodaddyOSS
github_username:  godaddy
analytics_id: UA-37178807-20

permalink: pretty

sass:
  sass_dir: ./_sass
  style: compressed

applicant_source: APPLICANT_SOURCE-3-119